name: Attendance System CI

on:
  push:
    branches:
      - main
    paths:
      - 'simpleprojects/attendance-system/**'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./simpleprojects/attendance-system/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test